aws_ssh_key: TFM_keypair
vpc_id: vpc-e855b591
ami_id: ami-096f43ef67d75e998 # Deep Learning Base AMI (Ubuntu 18.04) Version 23.0

instance_count: 1

#instance_type: t2.small
#instance_type: t3a.xlarge
instance_type: c5a.4xlarge

#security_group: P3forI4-sg
security_group: all-open

region: eu-west-1

zone: eu-west-1b

# tag to identify instances for cleanup
instance_tag: dl-experiment

python:
  version: 3.7
  virtualenv: /home/ec2-user/.venv
